### ISSUE TITLE
Text() method causes WDA error on xcode 11 and iOs 13

### ISSUE THREAD

**Issue by xd2006** [AirtestProject/iOS-Tagent#121]
xcode 11.2
ios 13.2.2

Using Airtest Text() method causes WDA error:
Traceback (most recent call last):
  File "airtest\cli\runner.py", line 65, in runTest
  File "site-packages\six.py", line 693, in reraise
  File "airtest\cli\runner.py", line 61, in runTest
  File "D:\airtest\test.air\test.py", line 13, in <module>
    text('754757')
  File "airtest\utils\logwraper.py", line 78, in wrapper
  File "airtest\core\api.py", line 367, in text
  File "C:\IDEs\Airtest\AirtestIDE_2019-09-11_py3_win64\airtest\core\ios\ios.py", line 45, in wrapper
    raise err
  File "C:\IDEs\Airtest\AirtestIDE_2019-09-11_py3_win64\airtest\core\ios\ios.py", line 38, in wrapper
    return func(self, *args, **kwargs)
  File "C:\IDEs\Airtest\AirtestIDE_2019-09-11_py3_win64\airtest\core\ios\ios.py", line 249, in text
    self.session.send_keys(text)
  File "site-packages\wda\__init__.py", line 459, in send_keys
  File "site-packages\wda\__init__.py", line 101, in fetch
  File "site-packages\wda\__init__.py", line 107, in _fetch_no_alert
  File "site-packages\wda\__init__.py", line 83, in httpdo
wda.WDAError: WDAError(status=13, value=-[XCUIApplication resolve]: unrecognized selector sent to instance 0x2801e4a10

(
	0   CoreFoundation                      0x00000001bcd1fac4 046F17DF-03A8-3D03-99F5-BD4CFF8123C4 + 1256132
	1   libobjc.A.dylib                     0x00000001bca39028 objc_exception_throw + 60
	2   CoreFoundation                      0x00000001bcc1df10 046F17DF-03A8-3D03-99F5-BD4CFF8123C4 + 200464
	3   CoreFoundation                      0x00000001bcd24254 046F17DF-03A8-3D03-99F5-BD4CFF8123C4 + 1274452
	4   CoreFoundation                      0x00000001bcd263f0 _CF_forwarding_prep_0 + 96
	5   WebDriverAgentLib                   0x0000000104f98b0c __53-[XCUIElement(FBUtilities) fb_waitUntilFrameIsStable]_block_invoke + 40
	6   WebDriverAgentLib                   0x0000000104f8fe94 -[FBRunLoopSpinner spinUntilTrue:error:] + 152
	7   WebDriverAgentLib                   0x0000000104f98a90 -[XCUIElement(FBUtilities) fb_waitUntilFrameIsStable] + 284
	8   WebDriverAgentLib                   0x0000000104f8c458 +[FBKeyboard waitUntilVisibleWithError:] + 64
	9   WebDriverAgentLib                   0x0000000104f8c0ac +[FBKeyboard typeText:frequency:error:] + 68
	10  WebDriverAgentLib                   0x0000000104fa5ee0 +[FBElementCommands handleKeys:] + 320
	11  WebDriverAgentLib                   0x0000000104f8f14c -[FBRoute_TargetAction mountRequest:intoResponse:] + 132
	12  WebDriverAgentLib                   0x0000000104f89b34 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 364
	13  RoutingHTTPServer                   0x00000001050363cc -[RoutingHTTPServer handleRoute:withRequest:response:] + 144
	14  RoutingHTTPServer                   0x0000000105036b80 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 44
	15  libdispatch.dylib                   0x00000001bc9c5fd8 D174E751-B542-3A69-A593-7AA69CF30F23 + 12248
	16  libdispatch.dylib                   0x00000001bc9d28d0 D174E751-B542-3A69-A593-7AA69CF30F23 + 63696
	17  libdispatch.dylib                   0x00000001bc9c5fd8 D174E751-B542-3A69-A593-7AA69CF30F23 + 12248
	18  libdispatch.dylib                   0x00000001bc9d1cc8 _dispatch_main_queue_callback_4CF + 968
	19  CoreFoundation                      0x00000001bcc9ae0c 046F17DF-03A8-3D03-99F5-BD4CFF8123C4 + 712204
	20  CoreFoundation                      0x00000001bcc95b68 046F17DF-03A8-3D03-99F5-BD4CFF8123C4 + 691048
	21  CoreFoundation                      0x00000001bcc95084 CFRunLoopRunSpecific + 480
	22  Foundation                          0x00000001bcfda3d0 D2B43A39-F0D5-30D3-9776-956A0F143802 + 33744
	23  WebDriverAgentLib                   0x0000000104f89070 -[FBWebServer startServing] + 304
	24  WebDriverAgentRunner                0x0000000104f73bd4 -[UITestingUITests testRunner] + 120
	25  CoreFoundation                      0x00000001bcd265a4 046F17DF-03A8-3D03-99F5-BD4CFF8123C4 + 1283492
	26  CoreFoundation                      0x00000001bcbef1d0 046F17DF-03A8-3D03-99F5-BD4CFF8123C4 + 8656
	27  XCTest                              0x0000000102e06950 __24-[XCTestCase invokeTest]_block_invoke_2.218 + 72
	28  XCTest                              0x0000000102e7a35c -[XCTMemoryChecker _assertInvalidObjectsDeallocatedAfterScope:] + 76
	29  XCTest                              0x0000000102e10dc8 -[XCTestCase assertInvalidObjectsDeallocatedAfterScope:] + 116
	30  XCTest                              0x0000000102e068d4 __24-[XCTestCase invokeTest]_block_invoke.212 + 204
	31  XCTest                              0x0000000102e5f3b8 -[XCTestCase(Failures) performFailableBlock:testCaseRun:shouldInterruptTest:] + 72
	32  XCTest                              0x0000000102e5f2c8 -[XCTestCase(Failures) _performTurningExceptionsIntoFailuresInterruptAfterHandling:block:] + 112
	33  XCTest                              0x0000000102e0633c __24-[XCTestCase invokeTest]_block_invoke + 1092
	34  XCTest                              0x0000000102e66720 -[XCUITestContext performInScope:] + 136
	35  XCTest                              0x0000000102e05e0c -[XCTestCase testContextPerformInScope:] + 188
	36  XCTest                              0x0000000102e05ee4 -[XCTestCase invokeTest] + 156
	37  XCTest                              0x0000000102e07cf0 __26-[XCTestCase performTest:]_block_invoke_2 + 48
	38  XCTest                              0x0000000102e5f3b8 -[XCTestCase(Failures) performFailableBlock:testCaseRun:shouldInterruptTest:] + 72
	39  XCTest                              0x0000000102e5f2c8 -[XCTestCase(Failures) _performTurningExceptionsIntoFailuresInterruptAfterHandling:block:] + 112
	40  XCTest                              0x0000000102e07c04 __26-[XCTestCase performTest:]_block_invoke.352 + 112
	41  XCTest                              0x0000000102e72cf8 +[XCTContext runInContextForTestCase:block:] + 216
	42  XCTest                              0x0000000102e073a0 -[XCTestCase performTest:] + 676
	43  XCTest                              0x0000000102e4b8f0 -[XCTest runTest] + 64
	44  XCTest                              0x0000000102e01b68 __27-[XCTestSuite performTest:]_block_invoke + 284
	45  XCTest                              0x0000000102e013e0 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 76
	46  XCTest                              0x0000000102e016c4 -[XCTestSuite performTest:] + 344
	47  XCTest                              0x0000000102e4b8f0 -[XCTest runTest] + 64
	48  XCTest                              0x0000000102e01b68 __27-[XCTestSuite performTest:]_block_invoke + 284
	49  XCTest                              0x0000000102e013e0 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 76
	50  XCTest                              0x0000000102e016c4 -[XCTestSuite performTest:] + 344
	51  XCTest                              0x0000000102e4b8f0 -[XCTest runTest] + 64
	52  XCTest                              0x0000000102e01b68 __27-[XCTestSuite performTest:]_block_invoke + 284
	53  XCTest                              0x0000000102e013e0 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 76
	54  XCTest                              0x0000000102e016c4 -[XCTestSuite performTest:] + 344
	55  XCTest                              0x0000000102e4b8f0 -[XCTest runTest] + 64
	56  XCTest                              0x0000000102e85208 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke + 180
	57  XCTest                              0x0000000102e85314 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke.84 + 116
	58  XCTest                              0x0000000102e1b56c -[XCTestObservationCenter _observeTestExecutionForBlock:] + 520
	59  XCTest                              0x0000000102e84fbc -[XCTTestRunSession runTestsAndReturnError:] + 624
	60  XCTest                              0x0000000102de5378 -[XCTestDriver runTestsAndReturnError:] + 444
	61  XCTest                              0x0000000102e6f080 _XCTestMain + 2404
	62  WebDriverAgentRunner-Runner         0x00000001029378e8 -[_XCTRunnerAppDelegate applicationWillResignActive:] + 0
	63  WebDriverAgentRunner-Runner         0x00000001029377f0 _XCTRunnerRunTests + 0
	64  CoreFoundation                      0x00000001bcc9b068 046F17DF-03A8-3D03-99F5-BD4CFF8123C4 + 712808
	65  CoreFoundation                      0x00000001bcc9a7ec 046F17DF-03A8-3D03-99F5-BD4CFF8123C4 + 710636
	66  CoreFoundation                      0x00000001bcc957ec 046F17DF-03A8-3D03-99F5-BD4CFF8123C4 + 690156
	67  CoreFoundation                      0x00000001bcc95084 CFRunLoopRunSpecific + 480
	68  GraphicsServices                    0x00000001c6ee3534 GSEventRunModal + 108
	69  UIKitCore                           0x00000001c0e05670 UIApplicationMain + 1940
	70  WebDriverAgentRunner-Runner         0x0000000102937ab4 main + 192
	71  libdyld.dylib                       0x00000001bcb14e18 2DE87B30-2CB1-30C2-9C0E-4BB9022D71E8 + 3608
))

[text_command_trace.txt](https://github.com/AirtestProject/iOS-Tagent/files/3851966/text_command_trace.txt)

**Comment by EraChen233** [comment]
Try updating the latest iOS-Tagent. We released a new version on 11-05.

**Comment by xd2006** [comment]
Yes, I'm alreadt using this Tagent version

**Comment by zhum26zhum** [comment]
Sorry,the issue will be fixed in next update.Please wait for update.

**Comment by zhum26zhum** [comment]
新版本已经更新，text接口调用报错已解决。欢迎反馈

**Comment by HeiTanBc** [comment]
> 新版本已经更新，text接口调用报错已解决。欢迎反馈

刚测试text的确没问题，但是似乎出了新的bug。click不准，控件点击失效或者点击两次

**Comment by zhum26zhum** [comment]
谢谢你，已经复现了，正在修。。。

**Comment by zhum26zhum** [comment]
点击异常已修复

**Comment by HeiTanBc** [comment]
> 点击异常已修复

谢谢
