### ISSUE TITLE
start_app("xxxxx")报错

### ISSUE THREAD

**Issue by lwjun1994** [AirtestProject/iOS-Tagent#169]
ios-tagent  5.27的
iOS12.4
Xcode 11.2.1
python airtest库 1.1.14

使用AirtestIDE运行start_app()正常
使用python或是命令行调用start_app()失败
报错信息：

/Users/zhaoyue/PycharmProjects/AirtestProject/venv/bin/python /Users/zhaoyue/PycharmProjects/AirtestProject/TestDemos/airtestText.py
Traceback (most recent call last):
  File "/Users/zhaoyue/PycharmProjects/AirtestProject/TestDemos/airtestText.py", line 27, in <module>
    start_app('com.google.chrome.ios')
  File "/Users/zhaoyue/PycharmProjects/AirtestProject/venv/lib/python3.7/site-packages/airtest/utils/logwraper.py", line 71, in wrapper
    res = f(*args, **kwargs)
  File "/Users/zhaoyue/PycharmProjects/AirtestProject/venv/lib/python3.7/site-packages/airtest/core/api.py", line 150, in start_app
    G.DEVICE.start_app(package, activity)
  File "/Users/zhaoyue/PycharmProjects/AirtestProject/venv/lib/python3.7/site-packages/airtest/core/ios/ios.py", line 259, in start_app
    self.session.start_app_new(package)
  File "/Users/zhaoyue/PycharmProjects/AirtestProject/venv/lib/python3.7/site-packages/airtest/core/ios/wda_client.py", line 415, in start_app_new
    return self.http.post('/wda/apps/launch', data=data)
  File "/Users/zhaoyue/PycharmProjects/AirtestProject/venv/lib/python3.7/site-packages/airtest/core/ios/wda_client.py", line 101, in fetch
    return self._fetch_no_alert(method, url, data)
  File "/Users/zhaoyue/PycharmProjects/AirtestProject/venv/lib/python3.7/site-packages/airtest/core/ios/wda_client.py", line 107, in _fetch_no_alert
    return httpdo(target_url, method, data)
  File "/Users/zhaoyue/PycharmProjects/AirtestProject/venv/lib/python3.7/site-packages/airtest/core/ios/wda_client.py", line 83, in httpdo
    raise WDAError(r.status, r.value)
airtest.core.ios.wda_client.WDAError: WDAError(status=1, value=Unhandled endpoint: /session/F0B0419D-69AC-49AB-8C40-16A0F815405B/wda/apps/launch -- http://127.0.0.1:8100/ with parameters {
    wildcards =     (
        "session/F0B0419D-69AC-49AB-8C40-16A0F815405B/wda/apps/launch"
    );
})

Process finished with exit code 1

**Comment by jeniva** [comment]
请问一下你start_app是可以杀掉进程重新启动的吗，我更新后进程杀不了了

**Comment by js779727785** [comment]
Airtest最新包存在的问题，降级到1.1.13就可以了；
你的IDE可以用是因为你用的不是最新的IDE，里面内置的Airtest是<=1.1.13的

**Comment by sdan227** [comment]
@lwjun1994   请问你的问题解决了么？我也遇到了同样的问题卡住了。本地airtest1.1.4，IDE airtest版本1.2.5 都报错，xcode11.3.1，手机试了几个系统版本都报同样的错误
