### ISSUE TITLE
poco.exceptions.PocoNoSuchNodeException: Cannot find any visible node by query UIObjectProxy of "XX"

### ISSUE THREAD

**Issue by MrYangzs** [AirtestProject/iOS-Tagent#202]
iOS ：
    xcode 11.4
    iPhone 6s  12.0系统

more = poco('查看更多')
if more.exists:
    print('查看更多--',more)
    more.click()

执行上段代码，print会输出，more.click()报错

[Start running..]
save log in '/var/folders/lp/fyxy6frn0d7grbt0m09t541h0000gn/T/AirtestIDE/scripts/516813e7d4717c6e12c6c9506ad807dc'
[09:19:44][DEBUG]<airtest.core.api> using path: /Users/yinai/Desktop/iOS-Tagent/未命名文件夹/ios_method_common.air
查看更多--
UIObjectProxy of "查看更多"
======================================================================
ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 26, in wrapped
    proxy.wait_for_appearance(timeout=proxy.poco._pre_action_wait_for_appearance)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 681, in wait_for_appearance
    raise PocoTargetTimeout('appearance', self)
poco.exceptions.PocoTargetTimeout: Waiting timeout for appearance of "UIObjectProxy of "查看更多""

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "airtest/cli/runner.py", line 73, in runTest
  File "site-packages/six.py", line 703, in reraise
  File "airtest/cli/runner.py", line 70, in runTest
  File "/Users/yinai/Desktop/iOS-Tagent/未命名文件夹/fisrtPage.air/fisrtPage.py", line 68, in <module>
    more.click()
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 29, in wrapped
    raise e
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 23, in wrapped
    return func(proxy, *args, **kwargs)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 332, in click
    pos_in_percentage = self.get_position(focus)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 72, in wrapped
    return func(proxy, *args, **kwargs)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 613, in get_position
    pos = self.attr('pos')
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 39, in wrapped
    return func(self, *args, **kwargs)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 734, in attr
    nodes = self._do_query(multiple=False)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 874, in _do_query
    raise PocoNoSuchNodeException(self)
poco.exceptions.PocoNoSuchNodeException: Cannot find any visible node by query UIObjectProxy of "查看更多"

----------------------------------------------------------------------
Ran 1 test in 9.210s

FAILED (errors=1)
[Finished]

**Comment by Sarahlunar** [comment]
这个问题解决了吗，我也遇到了同样的问题～～～
