### ISSUE TITLE
Can't use Poco: No such file or directory 'iproxy'

### ISSUE THREAD

**Issue by Noxalus** [AirtestProject/iOS-Tagent#26]
Hello everyone,

I followed the [documentation](https://airtest.netease.com/docs/en/1_online_help/Connecting_iOS.html) to connect an iOS device to my laptop through AirTest IDE, and it's working as expected, I can control the device in AirTest IDE directly, connecting to `http://127.0.0.1:8001` (so I've installed and ran `iproxy`).

Unfortunatly, my test script needs to use Poco for Unity (which is supported according to the README of this project):

```
# -*- encoding=utf8 -*-

from airtest.core.api import *

import time
from poco.drivers.unity3d import UnityPoco

poco = UnityPoco()
```

And it fails on this line:

```
poco = UnityPoco()
```

Here is the complete stacktrace:

```
[Start running..]
save log in '/var/folders/j_/qdbqhp992g944330r5h1sd205_xnfy/T/AirtestIDE/scripts/19d251a0ab1e2b60983b91f19f153961'
======================================================================
ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/cli/runner.py", line 66, in runTest
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/six.py", line 693, in reraise
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/cli/runner.py", line 62, in runTest
  File "/Users/Test.py", line 16, in <module>
    poco = UnityPoco()
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/drivers/unity3d/unity3d_poco.py", line 57, in __init__
    super(UnityPoco, self).__init__(addr[1], dev, **options)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/drivers/std/__init__.py", line 99, in __init__
    local_port, _ = self.device.instruct_helper.setup_proxy(port)
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/utils/retry.py", line 46, in f2
  File "/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/ios/instruct_helper.py", line 40, in setup_proxy
    self.do_proxy(local_port, remote_port)
  File "/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/ios/instruct_helper.py", line 58, in do_proxy
    stderr=subprocess.PIPE
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'iproxy': 'iproxy'
```

Moreover, the hierarchy doesn't appear in the *Pöco Assistant* when I select **Unity**.

Did I miss something?

**Comment by Meteorix** [comment]
did you do this step? https://github.com/AirtestProject/iOS-Tagent#2-set-up-proxy

**Comment by Noxalus** [comment]
Thank for the answer @Meteorix 

Yes I did (as said in my original message), `iproxy` is available in my terminal, and I can connect to the iOS device using `127.0.0.1:8001` from AirTest (which is not the case if `iproxy` doesn't run).

The problem only occurs with Poco, and I don't really understand why :/

**Comment by Meteorix** [comment]
I see... you can try starting AirtestIDE with cmd line:

```
$ cd /Applications/AirtestIDE.app/Contents/MacOS
$ ./AirtestIDE
```

**Comment by Noxalus** [comment]
It seems to work, thank you very much!

Does it mean that `iproxy` was only in the PATH of my current terminal context? Because even if I close all terminals and open a new one, I've still access to `iproxy` command, that's really weird.

But even if it's not an ideal solution, I will use it, thank again ;)

**Comment by Meteorix** [comment]
haha, thanks for you feedback.

See if we can fix this issue in AirtestIDE @brantxiong @yimelia

**Comment by phantomsom** [comment]
I have the above issue as well, connected airtest, 127.0.0.1/8100:status json works, but No such file or directory :'iproxy': 'iproxy" when running the project

AirtestIDE version 1.2.0
MacOS mojave 14.4

**Comment by EraChen233** [comment]
> I see... you can try starting AirtestIDE with cmd line:
> 
> ```
> $ cd /Applications/AirtestIDE.app/Contents/MacOS
> $ ./AirtestIDE
> ```

@phantomsom  Did you try this ?
What's the output msg?

**Comment by rere332** [comment]
any updated

**Comment by rere332** [comment]
i have the same issue, any ideas?

**Comment by EraChen233** [comment]
> I see... you can try starting AirtestIDE with cmd line:
> 
> ```
> $ cd /Applications/AirtestIDE.app/Contents/MacOS
> $ ./AirtestIDE
> ```

@rere332 Did you try this?

**Comment by rere332** [comment]
> > I see... you can try starting AirtestIDE with cmd line:
> > ```
> > $ cd /Applications/AirtestIDE.app/Contents/MacOS
> > $ ./AirtestIDE
> > ```
> 
> @rere332 Did you try this?

yes, i tried it, can't work.

when i run the following code in airtestIDE, i still have problems:
==============================
from airtest.core.api import *

auto_setup(__file__)


from poco.drivers.unity3d import UnityPoco
poco = UnityPoco()
sleep(3)
poco("ButtonCN").click()
================================
Errors:


[Start running..]
save log in '/var/folders/qv/s0rq4mh9585b_f7jnpddxzk80000gn/T/AirtestIDE/scripts/279fe8aaf0ddb6bb78d9676d88fe866a'
[rpc]connected
======================================================================
ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/cli/runner.py", line 65, in runTest
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/six.py", line 693, in reraise
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/cli/runner.py", line 61, in runTest
  File "/Users/landy.wang/kids/airtest-demo/untitled2.air/untitled2.py", line 12, in <module>
    poco("ButtonCN").click()
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 23, in wrapped
    return func(proxy, *args, **kwargs)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 332, in click
    pos_in_percentage = self.get_position(focus)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 72, in wrapped
    return func(proxy, *args, **kwargs)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 613, in get_position
    pos = self.attr('pos')
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 39, in wrapped
    return func(self, *args, **kwargs)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 734, in attr
    nodes = self._do_query(multiple=False)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 872, in _do_query
    self._nodes = self.poco.agent.hierarchy.select(self.query, multiple)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/freezeui/hierarchy.py", line 90, in select
    return self.selector.select(query, multiple)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/sdk/Selector.py", line 78, in select
    return self.selectImpl(cond, multiple, self.getRoot(), 9999, True, True)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/sdk/Selector.py", line 71, in getRoot
    return self.dumper.getRoot()
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/freezeui/hierarchy.py", line 35, in getRoot
    root = Node(self.dumpHierarchy())
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/utils/simplerpc/utils.py", line 12, in new_func
    cb = func(*args, **kwargs)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/drivers/std/dumper.py", line 13, in dumpHierarchy
    return self.rpcclient.call("Dump", onlyVisibleNode)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/utils/simplerpc/rpcclient.py", line 58, in call
    self.conn.send(msg)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/utils/simplerpc/transport/tcp/main.py", line 32, in send
    self.c.send(msg_bytes)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/utils/simplerpc/transport/tcp/safetcp.py", line 32, in send
    sent = self.sock.send(msg[totalsent:])
BrokenPipeError: [Errno 32] Broken pipe
==============================

@EraChen233 , do you have any idea ?

**Comment by EraChen233** [comment]
@rere332 Your latest log message shows that your IDE has lost connection to your device. It has nothing to do with iproxy.

Please open a new issue for your problem and detail your environment.
