### ISSUE TITLE
Poco issue with airtest CLI: No module named poco.drivers.unity3d

### ISSUE THREAD

**Issue by Noxalus** [AirtestProject/iOS-Tagent#27]
Hello everyone,

I'm trying to start an AirTest test using the CLI method (so with the `airtest` command installed with [pip](https://pypi.org/project/pip/)).

I'm on MacOS High Sierra and I want to launch the test on a real iOS device (iPhone X), so I did something like that:

```
airtest run /Users/[MyUser]/wkspaces/Test.air --device ios:///http://127.0.0.1:8100/
```

With a python script as simple as that:

```
from airtest.core.api import *

import time
from poco.drivers.unity3d import UnityPoco

poco = UnityPoco()
```

And here are the logs:

```
do not save log
======================================================================
ERROR: runTest (airtest.cli.runner.AirtestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/airtest/cli/runner.py", line 66, in runTest
    six.reraise(*sys.exc_info())
  File "/Library/Python/2.7/site-packages/airtest/cli/runner.py", line 62, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "/Users/[MyUser]/wkspaces/Test.air/Test.py", line 4, in <module>
    from poco.drivers.unity3d import UnityPoco
ImportError: No module named poco.drivers.unity3d

----------------------------------------------------------------------
Ran 1 test in 0.310s

FAILED (errors=1)
```

Did I do something wrong?

**Comment by Noxalus** [comment]
For information, I could run the tests in command line without any error, but using the AirTest IDE binary, like this: 

```
"/Applications/AirtestIDE.app/Contents/MacOS/AirtestIDE" runner "/Users/[MyUser]/wkspaces/Test.air"  --device ios:///http://127.0.0.1:8100/
```

**Comment by Meteorix** [comment]
Poco needs to be installed

https://github.com/AirtestProject/Poco#installation

**Comment by Noxalus** [comment]
I'm so sorry for the dummy question... 😞 

Actually, it works a lot better after the installation 😜 

Thank you again for your help! 👍
