### ISSUE TITLE
ios运行非常不稳定，很容易与手机断开链接。几乎无法使用

### ISSUE THREAD

**Issue by raoqianghua** [AirtestProject/iOS-Tagent#55]
ios运行容易出现下面2个错误，非常不稳定
Xcode 10.1.2
iOS12.1
airtestide:1.2.1

第一个错误：

Traceback (most recent call last):
File "/Users/hongyangwei/Desktop/itcn\u5faa\u73af\u9884\u89c8.air/itcn\u5faa\u73af\u9884\u89c8.py", line 96, in 
swipe(Template(r"tpl1548153988753.png", record_pos=(-0.291, 0.465), resolution=(750, 1334)), vector=[-0.0466, -0.2925])
File "/Users/wjjn3033/dev/idestable/airtest/airtest/utils/logwraper.py", line 72, in wrapper
File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/api.py", line 301, in swipe
File "/Users/wjjn3033/dev/idestable/airtest/airtest/utils/logwraper.py", line 72, in wrapper
File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/cv.py", line 42, in loop_find
File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/ios/ios.py", line 203, in snapshot
File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/ios/ios.py", line 44, in wrapper
File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/ios/ios.py", line 37, in wrapper
File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/ios/ios.py", line 110, in window_size
File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/wda/init.py", line 448, in window_size
File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/wda/init.py", line 101, in fetch
File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/wda/init.py", line 107, in _fetch_no_alert
File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/wda/init.py", line 83, in httpdo
wda.WDAError: WDAError(status=889, value=Application is not running, possibly crashed)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/Users/wjjn3033/dev/idestable/airtest/airtest/cli/runner.py", line 66, in runTest
File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/six.py", line 693, in reraise
File "/Users/wjjn3033/dev/idestable/airtest/airtest/cli/runner.py", line 62, in runTest
File "/Users/hongyangwei/Desktop/itcn\u5faa\u73af\u9884\u89c8.air/itcn\u5faa\u73af\u9884\u89c8.py", line 110, in 
stop_app("com.ezviz.hikconnect")
File "/Users/wjjn3033/dev/idestable/airtest/airtest/utils/logwraper.py", line 72, in wrapper
File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/api.py", line 158, in stop_app
File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/ios/ios.py", line 267, in stop_app
File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/wda/init.py", line 256, in session
File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/wda/init.py", line 324, in init
File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/wda/init.py", line 101, in fetch
File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/wda/init.py", line 107, in _fetch_no_alert
File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/wda/init.py", line 83, in httpdo
wda.WDAError: WDAError(status=889, value=Application is not running, possibly crashed)

--------------------------------------------------------------
第二个错误：

Traceback (most recent call last):
File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
File "", line 2, in raise_from
File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1331, in getresponse
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 297, in begin
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 258, in _read_status
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 586, in readinto
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
File "", line 2, in raise_from
File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1331, in getresponse
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 297, in begin
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 258, in _read_status
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 586, in readinto
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/Users/wjjn3033/dev/idestable/airtest/airtest/cli/runner.py", line 66, in runTest
File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/six.py", line 693, in reraise
File "/Users/wjjn3033/dev/idestable/airtest/airtest/cli/runner.py", line 62, in runTest
File "/Users/hongyangwei/Desktop/itcn\u5faa\u73af\u9884\u89c8.air/itcn\u5faa\u73af\u9884\u89c8.py", line 120, in 
touch(Template(r"tpl1548154059704.png", record_pos=(0.0, 0.028), resolution=(750, 1334)))
File "/Users/wjjn3033/dev/idestable/airtest/airtest/utils/logwraper.py", line 72, in wrapper
File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/api.py", line 254, in touch
File "/Users/wjjn3033/dev/idestable/airtest/airtest/utils/logwraper.py", line 72, in wrapper
File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/cv.py", line 42, in loop_find
File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/ios/ios.py", line 159, in snapshot
File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/ios/ios.py", line 143, in _neo_wda_screenshot
File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/wda/init.py", line 101, in fetch
File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/wda/init.py", line 107, in _fetch_no_alert
File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/wda/init.py", line 75, in httpdo
File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/requests/api.py", line 58, in request
File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/requests/adapters.py", line 495, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

Ran 1 test in 1947.731s

FAILED (errors=1)

**Comment by tommyshen123** [comment]
第二个问题我也遇到了，很无解，，之前用都是好好的

**Comment by EraChen233** [comment]
Xcode 和 Iproxy输出是怎样的呢？可以截图贴上来吗？

**Comment by EraChen233** [comment]
@tommyshen123 
可以试一下更新最新版的iOS-Tagent 
这个issue长时间没更新，我先关闭了，如果还是有问题，再重新开issue，提供更多信息吧
