### ISSUE TITLE
ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=8100): Read timed out. (read timeout=60.0)升级之后IDE运行成功，python环境直接运行脚本提示

### ISSUE THREAD

**Issue by bittern** [AirtestProject/iOS-Tagent#88]
IDE升级到最新的版本，pip 也安装对应的airtest 1.1.0  以及pocoui 1.0.78
安装之后，只能IDE运行，无法通过Python环境运行
ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=8100): Read timed out. (read timeout=60.0)升级之后IDE运行成功，python环境直接运行脚本提示

**Comment by EraChen233** [comment]
检查一下 facebook-wda 的版本

**Comment by bittern** [comment]
facebook-wda                           0.3.9

> 检查一下 facebook-wda 的版本

是不是需要回退

**Comment by EraChen233** [comment]
试一下重新安装 facebook-wda
```
pip install facebook-wda==0.2.1
```

**Comment by bittern** [comment]
> 试一下重新安装 facebook-wda
> 
> ```
> pip install facebook-wda==0.2.1
> ```

安装0.2.1版本依然无法启动，同样的错误，还有别的可能原因吗

**Comment by EraChen233** [comment]
把运行命令的窗口截图出来，还有iproxy、xcode的log窗口是否有报错信息？

**Comment by EraChen233** [comment]
facebook-wda在重新安装之前要先卸载哦，pip uninstall facebook-wda

**Comment by bittern** [comment]
> facebook-wda在重新安装之前要先卸载哦，pip uninstall facebook-wda

et1.1.1: retry to connect, error: HTTPConnectionPool(host='localhost', port=8100): Read timed out. (read timeout=60.0)
Traceback (most recent call last):
  File "/Users/zyj/uitest/airtestui_ios/testcase/platformgroup/firepower/test_AnchorOpen.py", line 15, in setUp
    start_app("tv.douyu.test1")
  File "/Users/zyj/Library/Python/2.7/lib/python/site-packages/airtest/utils/logwraper.py", line 78, in wrapper
    res = f(*args, **kwargs)
  File "/Users/zyj/Library/Python/2.7/lib/python/site-packages/airtest/core/api.py", line 148, in start_app
    G.DEVICE.start_app(package, activity)
  File "/Users/zyj/Library/Python/2.7/lib/python/site-packages/airtest/core/ios/ios.py", line 259, in start_app
    self.driver.session(package)
  File "/Users/zyj/Library/Python/2.7/lib/python/site-packages/wda/__init__.py", line 278, in session
    res = self.http.post('session', data)
  File "/Users/zyj/Library/Python/2.7/lib/python/site-packages/wda/__init__.py", line 101, in fetch
    return self._fetch_no_alert(method, url, data)
  File "/Users/zyj/Library/Python/2.7/lib/python/site-packages/wda/__init__.py", line 107, in _fetch_no_alert
    return httpdo(target_url, method, data)
  File "/Users/zyj/Library/Python/2.7/lib/python/site-packages/wda/__init__.py", line 75, in httpdo
    response = requests.request(method, url, data=data, timeout=HTTP_TIMEOUT)
  File "/Library/Python/2.7/site-packages/requests-2.18.4-py2.7.egg/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests-2.18.4-py2.7.egg/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests-2.18.4-py2.7.egg/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests-2.18.4-py2.7.egg/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPConnectionPool(host='localhost', port=8100): Read timed out. (read timeout=60.0)




iproxy信息：
Requesting connecion to device handle == 35 (serial: 00008020-0001450A3AF8002E), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
recv failed: Resource temporarily unavailable
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 35 (serial: 00008020-0001450A3AF8002E), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
recv failed: Resource temporarily unavailable
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 35 (serial: 00008020-0001450A3AF8002E), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
recv failed: Resource temporarily unavailable
accepted connection, fd = 4
waiting for connection
Number of available devices == 1

**Comment by bittern** [comment]
其他条件不变，更换手机后正常运行；  原手机版本12.1.4  更改后手机版本：12.3.1；

**Comment by huluxin** [comment]
这个问题我的解决办法是降低facebook-wda的版本，python3.7.4，airtest==1.0.27 facebook-wda==0.3.6,保持这个版本运行没问题。

**Comment by bittern** [comment]
ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=8100): Read timed out. (read timeout=60.0) case总数为50，大概运行5个之后报此错误，有时候可以恢复，大概5~6min后成功；有时无法恢复，一直卡

**Comment by 1111111Aa** [comment]
> 这个问题我的解决办法是降低facebook-wda的版本，python3.7.4，airtest==1.0.27 facebook-wda==0.3.6,保持这个版本运行没问题。

请问这个airtest版本 是 ide的还是 python里安装的airtest包呀
